services:
  mongo:
    image: mongo:6
    container_name: edviron-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: edviron-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: edviron
      ME_CONFIG_BASICAUTH_PASSWORD: change-me
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  api:
    build: ./backend
    container_name: edviron-api
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/edviron
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  web:
    build: ./frontend
    container_name: edviron-web
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    environment:
      - VITE_API_BASE_URL=http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  mongo_data:
